replicaCount: 2

image:
  repository: ianarodyakina/api-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 3000

env:
  API_URL: "http://apiapp-service"
  API_KEY: "test_api_key"

resources:
  limits:
    cpu: "300m"
    memory: "300Mi"
  requests:
    cpu: "100m"
    memory: "100Mi"

readinessProbe:
  path: /health
  port: 3000
  initialDelaySeconds: 5
  periodSeconds: 10

livenessProbe:
  path: /health
  port: 3000
  initialDelaySeconds: 15
  periodSeconds: 20