# apiapp-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: apiapp-service
spec:
  type: LoadBalancer
  selector:
    app: apiapp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000